### ISSUE TITLE
create database schema (ER-Diagram)

### ISSUE THREAD

**Issue by Dino-Kupinic** [Dino-Kupinic/Schulbuchaktion#2]
**Describe this Feature**

Task can be found here:
https://www.htl-steyr.ac.at/intern/wiki/doku.php?id=el-it:itp2:umsetzung_it_projekte:exercises:schulbuchaktion

**Comment by PhyToN-xD** [comment]
![Image](https://github.com/Dino-Kupinic/Schulbuchaktion/assets/62502697/76cc308e-77cd-45e0-bdd2-f71a0fac89e6)
